### ISSUE TITLE
--build=release is broken

### ISSUE THREAD

**Issue by denizzzka** [Elronnd/bearlibterminal-dlang#6]
Any (my) application what uses this package isn't compiles with `--build=release` option:
```
$ dub build --build=release :example
Building package dlangui_bearlibterminal:example in /home/denizzz/Dev/dlangui_bearlibterminal/
Performing "release" build using dmd for x86_64.
dlangui 0.9.82: building configuration "external"...
/usr/include/dmd/phobos/std/uri.d(323,19): Deprecation: function std.utf.toUTF8 is deprecated - To be removed November 2017. Please use std.utf.encode instead.
dlangui_bearlibterminal ~master: building configuration "library"...
../../.dub/packages/bearlibterminal-1.5.2/bearlibterminal/source/terminal.d(254,15): Error: function BearLibTerminal.terminal.print cannot inline function
../../.dub/packages/bearlibterminal-1.5.2/bearlibterminal/source/terminal.d(216,6): Error: function BearLibTerminal.terminal.open cannot inline function
../../.dub/packages/bearlibterminal-1.5.2/bearlibterminal/source/terminal.d(218,6): Error: function BearLibTerminal.terminal.set cannot inline function
../../.dub/packages/bearlibterminal-1.5.2/bearlibterminal/source/terminal.d(220,6): Error: function BearLibTerminal.terminal.setf!dstring.setf cannot inline function
../../.dub/packages/bearlibterminal-1.5.2/bearlibterminal/source/terminal.d(220,6): Error: function BearLibTerminal.terminal.setf!string.setf cannot inline function
```

**Comment by moon-chilled** [comment]
Fixed in 21286f94f9c7ae2968d029e84a1115829b148cc3.

**Comment by denizzzka** [comment]
Still persists:
```
../../.dub/packages/bearlibterminal-1.5.2/bearlibterminal/source/terminal.d(254,15): Error: function BearLibTerminal.terminal.print cannot inline function
```

**Comment by moon-chilled** [comment]
> ../../.dub/packages/bearlibterminal-1.5.**2**/bearlibterminal/source/terminal.d(254,15): Error: function BearLibTerminal.terminal.print cannot inline function

You're still on version 1.5.2.  Try updating to 1.5.3.

EDIT: it looks like code.dlang.org still hasn't updated it yet, and there are 922 packages ahead of it.  It should be fixed once it's downloaded, though, so for now I guess just compile debug builds.

**Comment by denizzzka** [comment]
> You're still on version 1.5.2. Try updating to 1.5.3.

OOops!

I am installed it locally. Other error still exists:
```
../bearlibterminal-dlang/source/terminal.d(304,3): Error: unrecognized declaration
```

**Comment by denizzzka** [comment]
(Can not reopen this issue)

**Comment by moon-chilled** [comment]
Oops!  It should be fixed now.

**Comment by denizzzka** [comment]
Great, works! Thanks!
